### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by MEntOMANdo** [explosivo22/rinnaicontrolr#13]
As of 2022-10-01 05:00:00 UTC, I receive the following error trying to connect:

`HTTPError('401 Client Error: Unauthorized for url: https://s34ox7kri5dsvdr43bfgp6qh6i.appsync-api.us-east-1.amazonaws.com/graphql')
`

Looks like they changed endpoints, or changed security again.

**Comment by explosivo22** [comment]
Looks like something was changed. I will investigate and get something out as soon as I can. Thanks for reporting.

**Comment by brad07x** [comment]
I'm noticing the same behavior downstream in the HA integration today:

`aiorinnai.errors.RequestError: There was a response error while requesting https://s34ox7kri5dsvdr43bfgp6qh6i.appsync-api.us-east-1.amazonaws.com/graphql: 401, message='Unauthorized', url=URL('https://s34ox7kri5dsvdr43bfgp6qh6i.appsync-api.us-east-1.amazonaws.com/graphql')`

Installing different versions of the HA component make no difference.

Interestingly enough, I can't access my device through the official Android app either - I got a prompt for the module's initial Wi-Fi Setup instead of my previously (and currently registered/online) linked device.

Decided to log out of the app. On sign-in, I noticed a quick loading screen that does nothing and loops back to sign-in, with no further progress. 

Closing and re-opening app after this brings back the initial Wi-Fi Setup prompt. As a final thought, I ran through the same logout/clear storage processes and tried sign-in on LTE instead of my home wifi to make sure I wasn't getting the 401 due to an IP ban or similar. Same behavior. 

Am going to try from an iOS device in the next few hours to see if it is the same.

After observing issues with the official app, I'm curious if the problem is actually on Rinnai's end and is a temporary condition (or the official app is also having similar issues with the 401 this component is receiving).  

I did head to the basement to check - my Control-R module is apparently registered with their cloud infra - solid blue status LED.

Sorry if this isn't quite the right place to add my report since I'm using the HA integration - likely more related to your aiorinnai library, but I noticed there was already discussion here.

**Comment by explosivo22** [comment]
Definitely looks like an issue on Rinnai. I would investigate, but I am seeing the same App issues which means I really can't investigate further until I can login.

No worries on posting here.  All leads to almost the same place for me.

**Comment by guillochon** [comment]
I see the same issues in the iOS app. I also suspect it's on Rinnai's side. I was planning to call their support line tomorrow morning.

**Comment by explosivo22** [comment]
Looks like Rinnai may have gotten things back. My App is working now and I am seeing no errors as of this time. We will keep an eye on it for a bit and watch.

**Comment by dulitz** [comment]
Working again for me also (app and API); I think this was 100% their side. Not a good look for them...

**Comment by MEntOMANdo** [comment]
Yep, logs are clean now. Closing. Thanks for taking the time to look at it!!
